### ISSUE TITLE
run on CPU only without GPU

### ISSUE THREAD

**Issue by ABDOELSHEMY** [LongguangWang/SOF-VSR#1]
hi @LongguangWang 
thank you for your work
could you please show me how to run your code with cpu only, i try to add --cpu arg to demo_Vid4.py as parser.add_argument("--cpu", action="store_true",help="use cpu only") , then i run the test with 
 python demo_Vid4.py --video_name calendar --upscale_factor 4 --cpu  
but it give me this error 
Traceback (most recent call last):
  File "demo_Vid4.py", line 54, in <module>
    main(cfg)
  File "demo_Vid4.py", line 30, in main
    net.cuda()
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\cuda\__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
thank you

**Comment by LongguangWang** [comment]
Hi @ABDOELSHEMY 
Sorry for the inconvenience. 
We've made some modifications and now the code can run on cpu only. Please try it.
For any questions, please feel free to contact me.

**Comment by ABDOELSHEMY** [comment]
thank you for your great work
i test it and it work great, and the result are amazing, this my offical Video Super-Resolution from now, i think i can close this issuse now
